title: Brandon O. Salazar # your name (or website title) here
logo: "/images/circle-cropped.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MS:Mathematics-Data Science
  <br>
  BS:Mathematics
  <br>
  The University of Texas at Dallas 
  <br>
  Richardson, TX
  <br><br>
  <a href="https://www.linkedin.com/in/brandonosalazar/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-156816088-1 # your Google Analytics tracking ID here
