title: Brandon O. Salazar # your name (or website title) here
logo: "/images/41262801542_22fc235ff3_z - Copy (3).jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
Master of Science Mathematics, focus Data Science       
Bachelor of Science Mathematics (GPA 3.4), (Major GPA 3.67) 
The University of Texas at Dallas 

  <br><br>
  <a href="https://www.linkedin.com/in/brandonosalazar/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
